config/routes.rb
Rails.application.routes.draw do
  get 'guessed_letters/new'
  root  'static_pages#welcome'
  get   '/rules', to: 'static_pages#rules'
  resources :answers
  resources :games
  resources :guessed_letters
end

app/models/answer.rb
class Answer < ApplicationRecord
  has_one :game
  validates :word, uniqueness: { message: "already exists" }
  validates_format_of :word, with: /\A[A-Z][A-Z ]*[A-Z]\z/,
                             message: "must be uppercase letters and spaces, must start and end with letters"
  before_validation :upcase

  private

  def upcase
    word.upcase!
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :answer
  has_many :guessed_letters

  NUM_OF_LIVES = 10

  delegate :word, to: :answer

  def all_guessed_letters
    guessed_letters.pluck(:letter)
  end

  def contains_letter?(letter)
    word.include?(letter)
  end

  def guessed_already?(letter)
    all_guessed_letters.include?(letter)
  end

  def lives_remain
    NUM_OF_LIVES - (all_guessed_letters - word.chars).size
  end

  def won?
    (word.delete(' ').chars - all_guessed_letters).empty?
  end

  def lost?
    lives_remain <= 0
  end

  def display_all_guessed_letters
    all_guessed_letters.to_a.join
  end
end

app/models/guessed_letter.rb
class GuessedLetter < ApplicationRecord
  belongs_to :game
  validates :letter, uniqueness: { case_sensitive: false, 
                                   scope: :game_id,
                                   message: "has already been guessed" },
                     length:     { maximum: 1 }
  validates_format_of :letter, with: /\A[A-Z]\z/, message: "must be a uppercase letter"
  before_validation :upcase

  private

  def upcase
    letter.upcase!
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answer = Answer.new
    @answers = Answer.all
  end

  def create
    @answer = Answer.new(answer_params)

    if @answer.save
      redirect_to answers_url
    else
      render "edit"
    end
  end

  def destroy
    Answer.find(params[:id]).destroy
    redirect_to answers_url
  end

  private

  def answer_params
    params.require(:answer).permit(:word)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def create
    if Answer.count == 0
      render "no_answers"
    else
      answer = Answer.order("RANDOM()").first
      @game = Game.new(answer: answer)
      @game.save
      redirect_to @game
    end
  end

  def show
    @guess_letter = GuessedLetter.new(game_id: params[:id])
    @game = Game.find(params[:id])
  end
end

app/controllers/guessed_letters_controller.rb
class GuessedLettersController < ApplicationController
  def create
    @guess_letter = GuessedLetter.new(guess_letter_params)
    @game = Game.find(@guess_letter.game_id)

    if @guess_letter.save
      redirect_to @game
    else
      render "games/show"
    end
  end

  private

  def guess_letter_params
    params.require(:guessed_letter).permit(:letter, :game_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  end

  def rules
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'Hangman'
    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end
end

app/helpers/games_helper.rb
module GamesHelper
  UNREVEALED_LETTER = '*'.freeze

  def marked_answer(game)
    answer = game.word
    answer.chars.map do |c|
      game.guessed_already?(c) || c == ' ' ? c : UNREVEALED_LETTER
    end.join
  end

  def game_over_message(game)
    if game.won?
      "WON!"
    elsif game.lost?
      "LOST! The answer was #{game.word}"
    end
  end
end

app/helpers/guessed_letters_helper.rb
module GuessedLettersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <%= f.label :word, "Add a new answer:", class: 'label' %>
  <%= f.text_field :word, class: 'uppercase', autofocus: true %>
  <%= f.submit "Add"%>
<% end %>

app/views/answers/edit.html.erb
<% provide(:title, 'Answers') %>
<h1>Answers</h1>
<%= render 'form' %>

app/views/answers/index.html.erb
<% provide(:title, 'Answers') %>
<h1>Answers</h1>
<%= render 'form' %>
<ul>
  <% @answers.each do |answer| %>
    <li>
      <span class="answer"><%= answer.word %></span>
      |
      <%= link_to "delete", answer, method: :delete, 
                                    data: { confirm: "Do you want to delete the word?" },
                                    id: answer.id %>
    </li>
  <% end %>
</ul>

app/views/games/no_answers.html.erb
<p>Oops, we don't have any answers yet. How about create one <%= link_to "here", answers_path %>?</p>

app/views/games/show.html.erb
<%if !@game.won? && !@game.lost?%>
  <%= render 'guessed_letters/form' %>
<% end %>

<p class="answer"><%= marked_answer @game %></p>

<p>Guessed Letters: <%= @game.display_all_guessed_letters %></p>
<p>Lives Remaining: <%= @game.lives_remain %></p>

<%if @game.won? || @game.lost?%>
  <%= game_over_message @game %>
  <%= render 'shared/new_game_button' %>
<% end %>

app/views/guessed_letters/_form.html.erb
<div>
  <%= form_for @guess_letter do |f|%>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :letter, "Take a guess:", class: 'label'  %>
    <%= f.text_field :letter, class: 'uppercase', :maxlength => 1, autofocus: true %>

    <%= f.hidden_field :game_id, :value => @guess_letter.game_id %>

    <%= f.submit "Guess"%>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="footer-nav">
    <div class="center nav-links">
      <%= link_to "Home",   root_path %>
      <%= link_to "Answers", answers_path %>
    </div>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_new_game_button.html.erb
<%= form_for(:game, url: games_path) do |f| %>
  <%= f.submit "Start New Game"%>
<% end %>

app/views/static_pages/rules.html.erb
<% provide(:title, "Rules") %>
<h1>Hangman Rules</h1>
<p>Come on! Of course you know how to play the Hangman game!!!</p>

app/views/static_pages/welcome.html.erb
<% provide(:title, "Welcome") %>
<h1>Welcome to the Hangman game!</h1>

<%= render 'shared/new_game_button' %>

<p>Take a look at the <%= link_to "rules", rules_path %>!</p>
<p>See the list of all answers <%= link_to "here", answers_path %></p>